addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.5.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"        % "0.10.4")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"       % "0.11.0")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.9")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"      % "1.5.11")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.4.1")
